require('dotenv').config()

const PORT = process.env.PORT
const POSTGRESQL_HOST = process.env.POSTGRESQL_HOST
const POSTGRES_DATABASE = process.env.POSTGRES_DATABASE
const POSTGRES_PASSWORD = process.env.POSTGRES_PASSWORD
const POSTGRES_USER = process.env.POSTGRES_USER
const POSTGRES_PORT = process.env.POSTGRES_PORT

module.exports = {
  PORT,
  POSTGRESQL_HOST,
  POSTGRES_DATABASE,
  POSTGRES_PASSWORD,
  POSTGRES_USER,
  POSTGRES_PORT
}